### ISSUE TITLE
Hiding Private Archived Lists

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#333]
I know this bug was fixed. Has the fix been added to the latest docker images? If so then how do I implement:

HYPERKITTY_HIDE_PRIVATE_LISTS

Thanks,
Brian

**Comment by maxking** [comment]
I believe it should be available in the `latest` version, it was fixed quite a bit ago.

**Comment by brianemwd** [comment]
Well I am running the latest version so how do I implement it? I did not find any documentation on that. I added the setting to /opt/mailman/web/settings_local.py but it did not work.

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by maxking** [comment]
You don't need any specific settings in settings.py, have you changed the list's default archival settings from Postorius?

   Settings -> Archival -> Private Archives

There is a cron job that periodically syncs the configuration from Core to Hyperkitty, I *think* it runs daily. You can force run it by running:

```python manage.py runjobs daily``` 

From within the Mailman-web container.

**Comment by brianemwd** [comment]
I have. The archives are not showing except when you click on the By name or Newest links. Then they show up. In other words, the Hide Private check box is checked for Most Popular and Most Active but not By name or Newest:

 

https://lists.dorsheitzedek.net/hyperkitty/

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by maxking** [comment]
Are you using `latest` tag or `0.2` tag? They aren't the same and it seems you are still on Hyperkitty 1.2.1 (from the footer on your page)

`Powered by HyperKitty version 1.2.1. `

Let me build and push 0.2.

**Comment by brianemwd** [comment]
I used the 0.2 tag. I thought you recommend using the 0.2 tag for production servers?

 

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by maxking** [comment]
I do :)

There is also a `latest` tag which seemed to have created the confusion. I'll push an update very shortly, sorry for the confusion.

**Comment by brianemwd** [comment]
Thank you sir!

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by brianemwd** [comment]
I tried pulling the latest image:

 

#docker pull maxking/mailman-web:0.2

docker pull maxking/mailman-web:0.2

0.2: Pulling from maxking/mailman-web

Digest: sha256:92f4372f3f6afbefa24d09bb7c8cdcdf7f24c2a04da8d3fad8ed16b3acffcd12

Status: Image is up to date for maxking/mailman-web:0.2

 

 

docker pull maxking/mailman-web:0.2.3

Error response from daemon: manifest for maxking/mailman-web:0.2.3 not found

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by maxking** [comment]
Can you re-try pulling 0.2.3 tag? I just pushed them.

**Comment by brianemwd** [comment]
Well that did apply some new images, however Hyperkitty is still at version 1.2.1 and the previous private archive bug is still there.

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by maxking** [comment]
Sorry for the delay, I hit some snafu with tagging wrong version.

Can you retry, I tested locally with a deployment and checked 0.2.3 version was available.

**Comment by brianemwd** [comment]
I pulled the image and something new downloaded however, Hyperkitty is still showing 1.2.1 and the private archive bug is still there.

**Comment by brianemwd** [comment]
Can I please get a resolution to this? I still am operating under Hyerkitty 1.2.1 and nothing new is being pulled from the 0.2.3 tag.

**Comment by maxking** [comment]
I am not sure I am able to replicate your situation. Are you sure you are upgrading correctly? 

```
podman run --rm -e SECRET_KEY=something -it quay.io/maxking/mailman-web:0.2.3 bash
DATABASE_URL is not defined. Using sqlite database...
Creating log file for mailman web
Creating log file for uwsgi..
settings_local.py not found, it is highly recommended that you provide one
Using default configuration to run.

368 static files copied to '/opt/mailman-web-data/static'.
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_mailman3, django_q, hyperkitty, openid, postorius, sessions, sites, socialaccount
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sites.0001_initial... OK
  Applying django_mailman3.0001_initial... OK
  Applying django_mailman3.0002_maildomain... OK
  Applying django_q.0001_initial... OK
  Applying django_q.0002_auto_20150630_1624... OK
  Applying django_q.0003_auto_20150708_1326... OK
  Applying django_q.0004_auto_20150710_1043... OK
  Applying django_q.0005_auto_20150718_1506... OK
  Applying django_q.0006_auto_20150805_1817... OK
  Applying django_q.0007_ormq... OK
  Applying django_q.0008_auto_20160224_1026... OK
  Applying django_q.0009_auto_20171009_0915... OK
  Applying socialaccount.0001_initial... OK
  Applying socialaccount.0002_token_max_lengths... OK
  Applying socialaccount.0003_extra_data_default_dict... OK
  Applying hyperkitty.0001_initial... OK
  Applying hyperkitty.0002_auto_20150311_0913... OK
  Applying hyperkitty.0003_thread_starting_email... OK
  Applying hyperkitty.0004_archived_date_and_subject... OK
  Applying hyperkitty.0005_MailingList_list_id... OK
  Applying hyperkitty.0006_thread_on_delete... OK
  Applying hyperkitty.0007_allauth_20160808_1604... OK
  Applying hyperkitty.0008_django_mailman3_profile... OK
  Applying hyperkitty.0009_duplicate_persona_users... OK
  Applying hyperkitty.0010_email_sender_name... OK
  Applying hyperkitty.0011_email_parent... OK
  Applying hyperkitty.0012_thread_order_null... OK
  Applying hyperkitty.0013_mailinglist_id_1... OK
  Applying hyperkitty.0014_mailinglist_id_2... OK
  Applying hyperkitty.0015_mailinglist_id_3... OK
  Applying hyperkitty.0016_auto_20180309_0056... OK
  Applying hyperkitty.0017_file_attachments... OK
  Applying hyperkitty.0018_threadcategory_color... OK
  Applying hyperkitty.0019_auto_20190127_null_description... OK
  Applying openid.0001_initial... OK
  Applying postorius.0001_initial... OK
  Applying postorius.0002_auto_20160210_0721... OK
  Applying postorius.0003_drop_addressconfirmationprofile... OK
  Applying postorius.0004_create_email_template... OK
  Applying postorius.0005_auto_20180707_1107... OK
  Applying postorius.0006_auto_20180711_1359... OK
  Applying postorius.0007_auto_20180712_0536... OK
  Applying sessions.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
bash-4.4# pip list
Package             Version    
------------------- -----------
arrow               0.14.2     
blessed             1.15.0     
certifi             2019.6.16  
chardet             3.0.4      
decorator           4.4.0      
defusedxml          0.6.0      
dj-database-url     0.5.0      
Django              2.1.5      
django-allauth      0.39.1     
django-appconf      1.0.3      
django-compressor   2.3        
django-extensions   2.1.9      
django-gravatar2    1.4.2      
django-haystack     2.8.1      
django-mailman3     1.2.0      
django-picklefield  2.0        
django-q            1.0.1      
djangorestframework 3.9.4      
httplib2            0.13.0     
HyperKitty          1.2.2      
idna                2.8        
lockfile            0.12.2     
mailmanclient       3.2.2      
mysqlclient         1.4.2.post1
networkx            2.3        
oauthlib            3.0.1      
pip                 19.1.1     
postorius           1.2.4      
psycopg2            2.8.3      
python-dateutil     2.8.0      
python3-openid      3.1.0      
pytz                2019.1     
rcssmin             1.0.6      
requests            2.22.0     
requests-oauthlib   1.2.0      
rjsmin              1.1.0      
robot-detection     0.4        
setuptools          40.6.2     
six                 1.12.0     
typing              3.6.6      
urllib3             1.25.3     
uWSGI               2.0.18     
wcwidth             0.1.7      
Whoosh              2.7.4      
xapian-haystack     2.1.1      
WARNING: You are using pip version 19.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bash-4.4# 
```

See the above command that I *just* ran and the version of Hyperkitty is 1.2.2. I tried the same with `docker.io/maxking/mailman-web:latest` and it is same.

**Comment by brianemwd** [comment]
What command are you referring to specifically? Podman?

Here are the exact update commands I am running:

$ docker-compose stop
$ docker-compose rm
$ docker pull maxking/mailman-core:0.2
$ docker pull maxking/mailman-web:0.2
$ docker-compose up -d

What am I missing here?

**Comment by brianemwd** [comment]
It does seem Postorius gets updated btw just not Hyperkitty.

**Comment by maxking** [comment]
I had pushed and tagged the 0.2.3, but not 0.2 (both weren't pointing to the same image which seems to be causing the problem, like they should)

Can you re-try the same commands you mention above please? (Just make sure you are using 0.2 in the docker-compose.yaml file for mailman-web and mailman-core containers)

**Comment by brianemwd** [comment]
A newer image was downloaded for mailman-web and now I am running Hyperkitty 1.2.2. That is latest version for the docker images right? Regardless it did get upgraded. Thank you!

 

Have a great day!

 

Brian Carpenter

EMWD.com

brian@emwd.com

**Comment by maxking** [comment]
That's right, 1.2.2 is the latest stable version of Hyperkitty. A new one should be coming out soon :)

Closing this.
