### ISSUE TITLE
maxking/mailman-web:latest is more than one year old

### ISSUE THREAD

**Issue by richardbrinkman** [maxking/docker-mailman#543]
A `docker pull maxking/mailman-web:latest` downloads a year old image. I expect this command to download the latest stable release. On https://github.com/maxking/docker-mailman/releases version 0.4.2 is tagged 'latest'. Why is there a difference between the latest docker image and the latest git release of docker-mailman?

**Comment by maxking** [comment]
This should be fixed.

**Comment by richardbrinkman** [comment]
The issue is still not resolved. 
https://hub.docker.com/r/maxking/mailman-web/tags still shows the `latest` tag as being more than a year old.
So please reopen this issue or resolve the problem.
